# Generated by Django 3.1.7 on 2021-04-03 18:38

from django.db import migrations, models
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('zipcode', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('health_condition', multiselectfield.db.fields.MultiSelectField(choices=[('Cancer', 'Cancer'), ('Cerebrovascular Disease', 'Cerebrovascular Disease'), ('Chronic Kidney Disease', 'Chronic Kidney Disease'), ('Chronic Obstructive Pulmonary Disease', 'Chronic Obstructive Pulmonary Disease'), ('Heart Conditions', 'Heart Conditions'), ('Liver Disease', 'Liver Disease'), ('Solid Organ Transplantation', 'Solid Organ Transplantation'), ('Obesity', 'Obesity'), ('Pregnancy', 'Pregnancy'), ('Sickle Cell Disease', 'Sickle Cell Disease'), ('Type 2 Diabetes Mellitus', 'Type 2 Diabetes Mellitus'), ('Nuerologic Conditions', 'Nuerologic Conditions')], max_length=235)),
                ('group_living', models.BooleanField(default=False)),
                ('job', models.CharField(choices=[('Transportation', 'Transportation'), ('Logistics', 'Logistics'), ('Manufacturing', 'Manufacturing'), ('Educational', 'Educational'), ('Postal Service', 'Postal Service'), ('Food Service', 'Food Service'), ('Construction', 'Construction'), ('Finance', 'Finance'), ('Information Technology', 'Information Technology'), ('Communications', 'Communications'), ('Energy', 'Energy'), ('Firefighter', 'Firefighter'), ('Law Enforcement', 'Law Enforcement'), ('Media', 'Media'), ('Public Safety', 'Public Safety'), ('Public Health', 'Public Health'), ('Other', 'Other')], max_length=50)),
                ('vaccine_brands', models.CharField(choices=[('Pfizer-BioNTech', 'Pfizer-BioNTech'), ('Moderna', 'Moderna'), ('Johnson & Johnson', 'Johnson & Johnson')], max_length=20)),
            ],
        ),
    ]
