# Generated by Django 3.1.7 on 2021-04-03 06:19

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=25)),
                ('last_name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=20)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('zipcode', models.IntegerField()),
                ('date_of_birth', models.DateField()),
                ('age', models.IntegerField()),
                ('job', models.CharField(choices=[('Transportation', 'Transportation'), ('Logistics', 'Logistics'), ('Educational', 'Educational'), ('Postal Service', 'Postal Service'), ('Food Service', 'Food Service'), ('Construction', 'Construction'), ('Finance', 'Finance'), ('Information Technology', 'Information Technology'), ('Communications', 'Communications'), ('Energy', 'Energy'), ('Firefighter', 'Firefighter'), ('Law Enforcement', 'Law Enforcement'), ('Media', 'Media'), ('Public Safety', 'Public Safety'), ('Public Health', 'Public Health')], max_length=50)),
                ('phase_category', models.CharField(choices=[('1B', '1B'), ('1C', '1C')], max_length=20)),
                ('vaccine_brands', models.CharField(choices=[('Pfizer-BioNTech', 'Pfizer-BioNTech'), ('Moderna', 'Moderna'), ('Johnson & Johnson', 'Johnson & Johnson')], max_length=20)),
            ],
        ),
    ]
